# Scientific Python
. scipy (global)
. numpy (calcul)
. matplotlib (graphique)
. pandas (data)


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
square = np.zeros((5,5), dtype='uint8')
square

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=uint8)

In [4]:
type(square)

numpy.ndarray

In [5]:
square[0]

array([0, 0, 0, 0, 0], dtype=uint8)

In [6]:
square[3,4]

0

In [7]:
square[:2,:3]

array([[0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [9]:
square2 = np.random.normal(10,3,(5,5))
square2

array([[ 7.2347863 ,  8.77224508,  8.11274094,  5.92548739, 10.46825164],
       [10.87477895, 10.56065912, 11.2026586 , 16.12937151, 11.62948303],
       [13.05205608,  9.17928875,  7.69244639,  8.98993292, 10.15458861],
       [10.47769387, 12.18080291, 11.38232466, 10.34577472,  6.66891653],
       [ 6.41325969, 15.94671413, 10.56219635,  4.25308811,  8.08372397]])

In [10]:
square2.sum()

246.29327022999226

In [11]:
square2.sum(axis=0)

array([48.05257489, 56.63970999, 48.95236693, 45.64365465, 47.00496378])

In [12]:
square2.diagonal()

array([ 7.2347863 , 10.56065912,  7.69244639, 10.34577472,  8.08372397])

In [13]:
square2.sum(axis=0) > 50

array([False,  True, False, False, False])

In [15]:
# matrix multiplications
np.ones((5,5)) @ square2

array([[48.05257489, 56.63970999, 48.95236693, 45.64365465, 47.00496378],
       [48.05257489, 56.63970999, 48.95236693, 45.64365465, 47.00496378],
       [48.05257489, 56.63970999, 48.95236693, 45.64365465, 47.00496378],
       [48.05257489, 56.63970999, 48.95236693, 45.64365465, 47.00496378],
       [48.05257489, 56.63970999, 48.95236693, 45.64365465, 47.00496378]])

In [16]:
square2.shape

(5, 5)

In [17]:
square2.dtype

dtype('float64')

In [18]:
square2.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [19]:
print(square2)

[[ 7.2347863   8.77224508  8.11274094  5.92548739 10.46825164]
 [10.87477895 10.56065912 11.2026586  16.12937151 11.62948303]
 [13.05205608  9.17928875  7.69244639  8.98993292 10.15458861]
 [10.47769387 12.18080291 11.38232466 10.34577472  6.66891653]
 [ 6.41325969 15.94671413 10.56219635  4.25308811  8.08372397]]


In [ ]:
square2.__